"""Play a game INSIDE the trained world model, with your keyboard.

Every frame on the left is generated by the diffusion model from its previous K frames and
your key press; nothing on the left comes from a game engine. The right panel runs the
real game with the same keys, so you can watch them stay in sync (or drift apart).

    pip install pygame            (and: pip install crafter, for Crafter)
    python play.py --ckpt outputs/model_base_plus1500.pt       # toy game
    python play.py --ckpt outputs/crafter.pt                   # Crafter
    python play.py --ckpt outputs/crafter.pt --denoise_steps 1 # faster, blurrier
    python play.py --ckpt outputs/crafter.pt --autoplay        # random actions, just watch

Game keys:
    toy       arrows / WASD move the paddle
    crafter   WASD move, space = do (hit/collect), tab = sleep,
              r/t/f/p = place stone/table/furnace/plant, 1-6 = craft tools
              (same keys as Crafter's own GUI; no key = noop)

App keys:
    enter            reset both games (new world)
    delete/backspace re-sync: copy the real game's last frames into the world model
    = / -            more / fewer denoising steps (quality vs speed)
    .                pause
    esc              quit

Runs on NVIDIA (cuda), Apple Silicon (mps) or CPU.  DIAMOND equivalent: src/play.py + src/game/
"""
import argparse
import time

import numpy as np
import pygame
import torch

from wm.config import Config, build_denoiser, config_from_dict
from wm.data import to_tensor, to_uint8
from wm.envs import get_env
from wm.rollout import WorldModelEnv
from wm.sampler import Sampler

p = argparse.ArgumentParser()
p.add_argument("--ckpt", default="outputs/model_base_plus1500.pt")
p.add_argument("--denoise_steps", type=int, default=Config.denoise_steps)
p.add_argument("--fps", type=int, default=0, help="default: 12 toy, 8 crafter")
p.add_argument("--scale", type=int, default=0, help="screen pixels per game pixel")
p.add_argument("--no-real", dest="real", action="store_false", help="hide the real game panel")
p.add_argument("--seed", type=int, default=0)
p.add_argument("--autoplay", action="store_true", help="random actions instead of keyboard (just watch)")
p.add_argument("--ctx_noise", type=float, default=0.0,
               help="context noise at inference (only for models trained with --ctx_noise_max)")
p.add_argument("--device", default=None, help="cuda / mps / cpu (default: best available)")
p.add_argument("--max_frames", type=int, default=0, help="auto-quit after N frames (for testing)")
p.add_argument("--screenshot", default="", help="save a screenshot at exit (for testing)")
args = p.parse_args()

# ---- load the world model ---------------------------------------------------------
ck = torch.load(args.ckpt, map_location="cpu", weights_only=False)
cfg = config_from_dict(ck["cfg"])
spec = get_env(cfg.env)
model = build_denoiser(cfg)
model.load_state_dict(ck["model"])
model.eval()
model.ctx_noise_inference = args.ctx_noise
device = args.device or ("cuda" if torch.cuda.is_available() else "mps" if torch.backends.mps.is_available() else "cpu")
model.to(device)
sampler = Sampler(model, args.denoise_steps)
wm_env = WorldModelEnv(sampler)
K = cfg.K
torch.set_grad_enabled(False)
fps = args.fps or (8 if cfg.env == "crafter" else 12)
scale = args.scale or (12 if cfg.env == "toy" else max(1, 512 // cfg.img_size))

world_seed = args.seed
game = None


def reset():
    """The world model needs K real frames to start from (its 'memory'). We get them
    from the real game by taking K-1 noop steps, then hand them to the world model."""
    global game, world_seed
    game = spec.make(seed=world_seed)
    world_seed += 1
    frames, actions = [game.reset()], []
    for _ in range(K - 1):
        actions.append(0)
        frames.append(game.step(0)[0])
    seed_world_model(frames, actions)
    return frames, actions


def seed_world_model(frames, actions):
    obs = to_tensor(np.stack(frames[-K:]))[None].to(device)
    act = torch.tensor(actions[-(K - 1):], dtype=torch.long)[None].to(device)
    wm_env.reset(obs, act)


history_frames, history_actions = reset()
wm_frame = real_frame = history_frames[-1]
real_done = False

# ---- window ------------------------------------------------------------------------
pygame.init()
panel = cfg.img_size * scale
gap, header = 16, 56
n_panels = 2 if args.real else 1
screen = pygame.display.set_mode((n_panels * panel + (n_panels + 1) * gap, panel + header + gap))
pygame.display.set_caption(f"tiny-diamond: playing {cfg.env} inside the world model")
font = pygame.font.SysFont(None, 22)
clock = pygame.time.Clock()

KEYS = [(pygame.key.key_code(name), a) for name, a in spec.keymap.items()]
auto_rng = np.random.default_rng(args.seed)


def current_action(prev: int) -> int:
    if args.autoplay:
        return spec.random_policy(auto_rng, prev)
    keys = pygame.key.get_pressed()
    for k, a in KEYS:
        if keys[k]:
            return a
    return 0


def blit_frame(img: np.ndarray, x: int, label: str):
    surf = pygame.surfarray.make_surface(img.swapaxes(0, 1))
    surf = pygame.transform.scale(surf, (panel, panel))  # nearest-neighbour: keeps pixels crisp
    screen.blit(surf, (x, header))
    screen.blit(font.render(label, True, (230, 230, 230)), (x, header - 22))


paused, running, n, action, ms = False, True, 0, 0, 0.0
while running:
    for ev in pygame.event.get():
        if ev.type == pygame.QUIT:
            running = False
        elif ev.type == pygame.KEYDOWN:
            if ev.key == pygame.K_ESCAPE:
                running = False
            elif ev.key in (pygame.K_RETURN, pygame.K_KP_ENTER):
                history_frames, history_actions = reset()
                wm_frame = real_frame = history_frames[-1]
                real_done = False
            elif ev.key in (pygame.K_BACKSPACE, pygame.K_DELETE):  # re-sync world model to reality
                seed_world_model(history_frames, history_actions)
            elif ev.key == pygame.K_PERIOD:
                paused = not paused
            elif ev.key in (pygame.K_PLUS, pygame.K_EQUALS, pygame.K_KP_PLUS):
                sampler.n_steps = min(sampler.n_steps + 1, 20)
            elif ev.key in (pygame.K_MINUS, pygame.K_KP_MINUS):
                sampler.n_steps = max(sampler.n_steps - 1, 1)

    if not paused:
        action = current_action(action)
        t0 = time.time()
        wm_frame = to_uint8(wm_env.step(torch.tensor([action], device=device)))[0]  # <- the world model
        if device == "mps":
            torch.mps.synchronize()
        ms = (time.time() - t0) * 1000
        if not real_done:
            real_frame, real_done = game.step(action)                              # <- the real game
            history_frames.append(real_frame)
            history_actions.append(action)
            history_frames, history_actions = history_frames[-K:], history_actions[-K:]
        n += 1

    screen.fill((12, 12, 16))
    status = (f"action: {spec.action_names[action]:18s} denoise steps: {sampler.n_steps}   "
              f"model: {ms:4.0f} ms/frame on {device}   {'PAUSED' if paused else ''}")
    screen.blit(font.render(status, True, (160, 200, 255)), (gap, 8))
    blit_frame(wm_frame, gap, "WORLD MODEL (you are playing here)")
    if args.real:
        blit_frame(real_frame, 2 * gap + panel, "real game, same keys" + ("  (GAME OVER - enter)" if real_done else ""))
    pygame.display.flip()
    clock.tick(fps)

    if args.max_frames and n >= args.max_frames:
        running = False

if args.screenshot:
    pygame.image.save(screen, args.screenshot)
pygame.quit()
